Don't show a harmless/confusing warning on stdout.
Some Python versions will lead to the following message on stdout currently:

  srd: Attribute Error: Failed to load decoder common: no 'Decoder' \
  attribute in imported module: 'module' object has no attribute 'Decoder'

This is a harmless (though confusing for users) warning, since "common"
is not an actual PD and it shouldn't be loaded as PD (it just has to
be present).