Add a missing #include.
This causes compiler errors in some setups otherwise, e.g.:

  CC       libsigrokdecode_la-session.lo
session.c: In function 'srd_session_metadata_set':
session.c:195:46: error: expected ')' before 'PRIu64'
  srd_dbg("Setting session %d samplerate to %"PRIu64".",
                                              ^
session.c: In function 'srd_session_send':
session.c:242:15: error: expected ')' before 'PRIu64'
    "number %" PRIu64 ", %" PRIu64 " bytes at 0x%p",
               ^